sudo: required
dist: trusty

branches:
  only: master

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

matrix:
  include:
    - language: java
      jdk: oraclejdk8
      script:
        - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      before_script:
        - cd ./backend/

    - language: node_js
      node_js: stable
      install:
        - npm install
      script:
        - npm run ci
      before_script:
        - cd ./frontend/
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start
